version: '3.8'

services:
  api:
    build: .
    container_name: inventario_api
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: inventario_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: inventariodb
    ports:
      - "5432:5432"